/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connect.hub;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Etijah
 */
public class SearchFram extends javax.swing.JFrame {

    @SuppressWarnings("rawtypes")
    DefaultListModel daefaultListModel = new DefaultListModel();

    /**
     * Creates new form ScearchFram
     */
    public SearchFram() {
        initComponents();

        this.setVisible(true);
        setTitle("Friends Suggestions");
        setResizable(false);
        this.bindData();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        SearchPanel.setVisible(true);
    }

    @SuppressWarnings("rawtypes")
    private ArrayList getAccount() {
        ArrayList<String> accounts = new ArrayList<>();
        for (String key : FilesManagement.map.keySet()) {
            User acct = FilesManagement.map.get(key);
            if (!(ConnectHub.currentUser.getBlockedBy().contains(acct.getUserId()))) {
                accounts.add(acct.getUsername());
            }
        }
        return accounts;
    }

    @SuppressWarnings("unchecked")
    private void bindData() {
        ArrayList<String> accounts = getAccount();
        for (String c : accounts) {
            daefaultListModel.addElement(c);
        }
        accountList.setModel(daefaultListModel);
        accountList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    @SuppressWarnings({ "unchecked", "rawtypes" })
    private void searchFilter(String SearchTerm) {
        DefaultListModel filteredTtems = new DefaultListModel();
        ArrayList<String> accounts = getAccount();
        for (String c : accounts) {
            String accountName = c.toString().toLowerCase();
            if (accountName.contains(SearchTerm.toLowerCase())) {
                filteredTtems.addElement(c);
            }
        }
        daefaultListModel = filteredTtems;
        accountList.setModel(daefaultListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScearchBar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchPanel.setBackground(new java.awt.Color(255, 255, 255));

        ScearchBar.setColumns(20);
        ScearchBar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ScearchBar.setForeground(new java.awt.Color(153, 153, 153));
        ScearchBar.setRows(5);
        ScearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ScearchBarKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ScearchBar);

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-interface-symbol.png"))); // NOI18N

        accountList.setBackground(new java.awt.Color(204, 204, 204));
        accountList.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        accountList.setForeground(new java.awt.Color(255, 255, 255));
        accountList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(accountList);

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
                SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SearchPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301,
                                                Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addGap(44, 44, 44)));
        SearchPanelLayout.setVerticalGroup(
                SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SearchPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                .addGap(112, 112, 112)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(125, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_accountListMouseClicked
        ScearchBar.setText(accountList.getSelectedValue());
        Searching search = new Searching();
        User user = search.getUser(accountList.getSelectedValue());
        if (!(user.equals(null))) {
            try {
                new ProfileManagmentPage(user);
            } catch (IOException ex) {
                Logger.getLogger(SearchFram.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }// GEN-LAST:event_accountListMouseClicked

    private void ScearchBarKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_ScearchBarKeyReleased
        searchFilter(ScearchBar.getText());
    }// GEN-LAST:event_ScearchBarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFram.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFram.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFram.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFram.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ScearchBar;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JList<String> accountList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
